before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=17.12.1~ce-0~ubuntu
  - nvm install --lts node
  - docker swarm init
language: java
script:
  - make test
services:
  - docker
sudo: required
