version: '2'
services:
  # HOBBIT GUI
  gui:
    build: ./hobbit-gui/gui-serverbackend
    ports:
      - "8082:8080"
    networks:
      - hobbit-core
      - hobbit
    depends_on:
      - rabbit
      - virtuoso
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - KEYCLOAK_AUTH_URL=http://192.168.99.100:8181/auth
      - CHECK_REALM_URL=false
      - KEYCLOAK_DIRECT_URL=http://keycloak:8080/auth

  # Keycloak user management (used by the GUI)
  keycloak:
    image: git.project-hobbit.eu:4567/gitadmin/hobbit-keycloak:1.0.0
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    networks:
      - hobbit
    volumes:
      - ./config/keycloak:/opt/jboss/keycloak/standalone/data/db

  # HOBBIT Analysis component
  analysis:
    build: ./analysis-component
    networks:
      - hobbit-core
    depends_on:
      - rabbit
    environment:
      - HOBBIT_RABBIT_HOST=rabbit

  # message bus
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    networks:
      - hobbit
      - hobbit-core
    ports:
      - "8081:15672"
      # Forwarding the port for testing
      - "5672:5672"

  # DB for controller
  redis:
    image: redis
    networks:
      - hobbit-core
    ports:
      - "6379:6379"

  # Triple store
  virtuoso:
    image: openlink/virtuoso_opensource:vos
    container_name: vos
    hostname: vos
    volumes:
      - ./config/db:/opt/virtuoso-opensource/var/lib/virtuoso/db
    networks:
      - hobbit-core
    ports:
      - "8890:8890"

  # Storage service
  storage-service:
    build: ./platform-storage/storage-service
    networks:
      - hobbit-core
    environment:
      - SPARQL_ENDPOINT_URL=http://vos:8890/sparql
      - HOBBIT_RABBIT_HOST=rabbit
      - SPARQL_ENDPOINT_USERNAME=HobbitPlatform
      - SPARQL_ENDPOINT_PASSWORD=Password
    depends_on:
       - virtuoso

networks:
  hobbit:
    external:
      name: hobbit
  hobbit-core:
    external:
      name: hobbit-core
